import { useState } from 'react';
import { motion } from 'framer-motion';
import { useTheme } from '../../context/ThemeContext';
import { communityAPI } from '../../utils/api';
import ClayCard from '../../components/ui/ClayCard';
import toast from 'react-hot-toast';

const roles = [
  { value: 'donor',     label: '🍱 Donor'     },
  { value: 'rider',     label: '🚴 Rider'      },
  { value: 'ngo',       label: '🏠 NGO'        },
  { value: 'corporate', label: '🏢 Corporate'  },
  { value: 'community', label: '🌍 Community'  },
];

const postTypes = [
  { value: 'donation_story',       label: '🍱 Donation Story'     },
  { value: 'rescue_selfie',        label: '🚴 Rescue Story'        },
  { value: 'volunteer_experience', label: '🤝 Volunteer Story'     },
  { value: 'corporate_impact',     label: '🏢 Corporate Impact'    },
  { value: 'general',              label: '✍️ General Post'        },
];

const MAX_CHARS = 500;

const CreatePost = ({ onPost }) => {
  const { isDark } = useTheme();
  const [form, setForm] = useState({
    authorName: '',
    authorRole: 'community',
    postType:   'general',
    content:    '',
  });
  const [submitting, setSubmitting] = useState(false);
  const charsLeft = MAX_CHARS - form.content.length;

  const handleSubmit = async () => {
    if (!form.authorName.trim()) {
      toast.error('Please enter your name');
      return;
    }
    if (!form.content.trim() || form.content.length < 10) {
      toast.error('Please write at least 10 characters');
      return;
    }

    setSubmitting(true);
    try {
      const { data } = await communityAPI.createPost(form);
      const post = data.post || {
        _id:        `post-${Date.now()}`,
        ...form,
        likes:      0,
        comments:   [],
        isAutoGenerated: false,
        createdAt:  new Date().toISOString(),
      };
      toast.success('✍️ Story shared with the community!');
      if (onPost) onPost(post);
      setForm({
        authorName: '',
        authorRole: 'community',
        postType:   'general',
        content:    '',
      });
    } catch {
      const fallbackPost = {
        _id:        `post-${Date.now()}`,
        ...form,
        likes:      0,
        comments:   [],
        isAutoGenerated: false,
        createdAt:  new Date().toISOString(),
      };
      toast.success('Demo: Story shared! ✍️');
      if (onPost) onPost(fallbackPost);
    } finally {
      setSubmitting(false);
    }
  };

  return (
    <ClayCard>
      <h4
        className={`font-bold text-base mb-5 ${
          isDark ? 'text-white' : 'text-gray-900'
        }`}
      >
        ✍️ Share Your Story
      </h4>

      <div className="space-y-4">
        {/* Author Name */}
        <input
          type="text"
          placeholder="Your name or organisation"
          value={form.authorName}
          onChange={(e) =>
            setForm({ ...form, authorName: e.target.value })
          }
          className={`w-full p-4 rounded-2xl text-sm font-medium ${
            isDark
              ? 'bg-white/10 text-white border border-white/20 placeholder-gray-500'
              : 'bg-white shadow-clay text-gray-800'
          } focus:outline-none focus:ring-2 focus:ring-primary/40`}
        />

        {/* Role & Post Type Row */}
        <div className="grid grid-cols-2 gap-3">
          <div>
            <label
              className={`block text-xs font-bold mb-1.5 ${
                isDark ? 'text-gray-400' : 'text-gray-600'
              }`}
            >
              Role
            </label>
            <select
              value={form.authorRole}
              onChange={(e) =>
                setForm({ ...form, authorRole: e.target.value })
              }
              className={`w-full p-3 rounded-2xl text-sm font-medium ${
                isDark
                  ? 'bg-white/10 text-white border border-white/20'
                  : 'bg-white shadow-clay text-gray-800'
              } focus:outline-none`}
            >
              {roles.map((r) => (
                <option key={r.value} value={r.value}>
                  {r.label}
                </option>
              ))}
            </select>
          </div>

          <div>
            <label
              className={`block text-xs font-bold mb-1.5 ${
                isDark ? 'text-gray-400' : 'text-gray-600'
              }`}
            >
              Post Type
            </label>
            <select
              value={form.postType}
              onChange={(e) =>
                setForm({ ...form, postType: e.target.value })
              }
              className={`w-full p-3 rounded-2xl text-sm font-medium ${
                isDark
                  ? 'bg-white/10 text-white border border-white/20'
                  : 'bg-white shadow-clay text-gray-800'
              } focus:outline-none`}
            >
              {postTypes.map((t) => (
                <option key={t.value} value={t.value}>
                  {t.label}
                </option>
              ))}
            </select>
          </div>
        </div>

        {/* Content Textarea */}
        <div className="relative">
          <textarea
            rows={4}
            placeholder="Share your rescue story, impact milestone, or community update... 🌱"
            value={form.content}
            onChange={(e) => {
              if (e.target.value.length <= MAX_CHARS) {
                setForm({ ...form, content: e.target.value });
              }
            }}
            className={`w-full p-4 rounded-2xl text-sm font-medium resize-none ${
              isDark
                ? 'bg-white/10 text-white border border-white/20 placeholder-gray-500'
                : 'bg-white shadow-clay text-gray-800'
            } focus:outline-none focus:ring-2 focus:ring-primary/40`}
          />
          <span
            className={`absolute bottom-3 right-4 text-xs font-semibold ${
              charsLeft < 50
                ? 'text-red-400'
                : charsLeft < 100
                ? 'text-yellow-400'
                : 'text-gray-400'
            }`}
          >
            {charsLeft}
          </span>
        </div>

        {/* Hashtag Suggestions */}
        <div className="flex gap-2 flex-wrap">
          {['#ZeroWaste', '#FoodHero', '#ResQAI', '#SDG2', '#ClimateAction'].map(
            (tag) => (
              <motion.button
                key={tag}
                whileHover={{ scale: 1.06 }}
                whileTap={{ scale: 0.94 }}
                onClick={() => {
                  const newContent = form.content + ' ' + tag;
                  if (newContent.length <= MAX_CHARS) {
                    setForm({ ...form, content: newContent.trim() });
                  }
                }}
                className={`text-xs px-3 py-1 rounded-full font-semibold ${
                  isDark
                    ? 'bg-primary/10 text-primary hover:bg-primary/20'
                    : 'bg-blue-50 text-primary hover:bg-blue-100'
                } transition-all`}
              >
                {tag}
              </motion.button>
            )
          )}
        </div>

        {/* Submit Button */}
        <motion.button
          whileHover={{ scale: 1.03 }}
          whileTap={{ scale: 0.97 }}
          onClick={handleSubmit}
          disabled={submitting || !form.content.trim() || !form.authorName.trim()}
          className="w-full py-4 rounded-2xl bg-gradient-to-r from-primary to-mint
            text-white font-extrabold text-base disabled:opacity-40 shadow-lg"
        >
          {submitting ? '📤 Sharing...' : '🌱 Share with Community'}
        </motion.button>
      </div>
    </ClayCard>
  );
};

export default CreatePost;